### ISSUE TITLE
 Some links being downloaded as empty m4a files

### ISSUE THREAD

**Issue by chdorter** [tizerk/ytiz#4]
**Describe the bug**
Some videos are being downloaded as m4a files with a size of 256 bytes.
The filename is correct.
The preview appears correct.
No numeric percentage progress appears, it just downloads instantly.
Using default settings (MP3, 128kbps)
Using basic YouTube links without parameters appended

**To Reproduce**
1. Open the page
2. Paste a YouTube link - eg: https://www.youtube.com/watch?v=8l75Z8wil_U
3. Click download

**Expected behavior**
The full size MP3 file should download.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (126.0.6478.127) and Edge (126.0.2592.87)

Great app!! Thanks!

**Comment by tizerk** [comment]
Thanks for bringing this up!  The yt-dlp version I was using was 2024.07.08, which has a bug with the YouTube extractor.  I've updated the backend to 2024.07.09, which should fix the issue.  I'll keep monitoring to make sure everything is working again.

EDIT: Okay, that wasn't the issue.  I'll look into this deeper.

**Comment by tizerk** [comment]
It seems yt-dlp was incorrectly labelling the files as .M4A, even when they were supposed to be .MP3.  I've forced the backend to rename M4A files to MP3, which should now fix the issue.  I'll keep monitoring to make sure everything is working again.

**Comment by chdorter** [comment]
Great! Looks like it's working smoothly now. Thanks for looking into this. Cheers again for making this useful tool
