### ISSUE TITLE
Request: Extend video length?

### ISSUE THREAD

**Issue by xandian97** [tizerk/ytiz#5]
I absolutely love this website, after years of trying to find Youtube to MP3 converters that weren't scams, it's such a relief to find one that just works!

My main request though, would be to extend the length of videos it can convert, if possible - I like to listen to and download a lot of ambient music mixes, most of which are between 1 and 2 hours in length. It would be amazing if YTiz could handle those.

**Comment by tizerk** [comment]
Sorry, I don't have any plans to extend the durations as of now.  Long content takes too much time to process on the server and costs me a lot more than short content.  Maybe at some point in the future, but no plans right now.
