### ISSUE TITLE
Can't download as FLAC :(

### ISSUE THREAD

**Issue by presolve0** [tizerk/ytiz#6]
Hi! any link like youtube.com / youtu.be / m.youtube.com / music.youtube.com I paste to **download as FLAC** file it says: 
**Error:  This URL is not supported.**
![brave_XG43PHRb89](https://github.com/user-attachments/assets/f6948a1a-b87e-4702-b3ec-11407cd1c5a7)
![brave_g9WsQUWQaJ](https://github.com/user-attachments/assets/257b6ad3-7c64-43e5-83aa-ccf954e33ec5)

Thank you for such a great project!

**Comment by tizerk** [comment]
Thanks for bringing this up.  
It seems the newer versions of yt-dlp require mutagen to embed metadata in FLAC files, which I had overlooked.  
I've installed mutagen on all the server instances now, so this issue should be fixed.
Let me know if there's still some issues.
